import AppKit
import Foundation

struct PrivacyFilter: Sendable {
    static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-remote-clipboard"
    ]

    static let defaultExcludedBundleIdentifiers: [String] = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.dashlane.dashlanephonefinal",
        "com.lastpass.LastPass",
        "com.lastpass.LastPassHelper",
        "com.roboform.RoboForm",
        "com.apple.Passwords",
        "com.apple.keychainaccess"
    ]

    var excludedBundleIdentifiers: Set<String>

    init(excludedBundleIdentifiers: [String]) {
        self.excludedBundleIdentifiers = Set(excludedBundleIdentifiers)
    }

    func shouldCapture(types: [NSPasteboard.PasteboardType], sourceBundleIdentifier: String?) -> Bool {
        let rawTypes = Set(types.map(\.rawValue))
        guard rawTypes.isDisjoint(with: Self.transientTypes) else {
            return false
        }
        if let sourceBundleIdentifier, excludedBundleIdentifiers.contains(sourceBundleIdentifier) {
            return false
        }
        return true
    }
}
